version: '3'
services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    #    expose:
    #      - 5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  application:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80



volumes:
  db-data:
